### ISSUE TITLE
Incompatible with my mod Cliffie's Goos

### ISSUE THREAD

**Issue by CliffracerX** [Hurricaaane/Presence-Footsteps#11]
Walking through/on any goo will crash my client with this errorlog:
`java.lang.NullPointerException: Unexpected error
    at eu.ha3.mc.presencefootsteps.mcpackage.implem.AcousticsManager.playStep(AcousticsManager.java:56)
    at eu.ha3.mc.presencefootsteps.game.system.PFSolver.playAssociation(PFSolver.java:64)
    at eu.ha3.mc.presencefootsteps.game.system.PFReaderH.playMultifoot(PFReaderH.java:362)
    at eu.ha3.mc.presencefootsteps.game.system.PFReaderH.simulateJumpingLanding(PFReaderH.java:284)
    at eu.ha3.mc.presencefootsteps.game.system.PFReaderH.simulateAirborne(PFReaderH.java:231)
    at eu.ha3.mc.presencefootsteps.game.system.PFReaderH.generateFootsteps(PFReaderH.java:67)
    at eu.ha3.mc.presencefootsteps.game.system.PFIsolator.onFrame(PFIsolator.java:51)
    at eu.ha3.mc.presencefootsteps.game.system.PFHaddon.onFrame(PFHaddon.java:359)
    at eu.ha3.mc.haddon.litemod.LiteBase.onTick(LiteBase.java:99)
    at com.mumfrey.liteloader.client.ClientEvents.onTick(ClientEvents.java:665)
    at com.mumfrey.liteloader.client.CallbackProxyClient.onTick(CallbackProxyClient.java:146)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`
Not sure if this is presence footsteps or liteloader being buggy, but it is kind of frustrating my users a bit.

**Comment by Sollace** [comment]
This is an issue that affects all mods that add blocks. Basically anything that doesn't have an entry in the blockmap.cfg in the resourcepack will crash when you walk on them. See https://github.com/Hurricaaane/Presence-Footsteps/issues/13

Until it can be fixed, you can avoid this problem by providing a resourcepack with a custom blockmap.cfg and pf_pack.json that PF can recognize. You can look to the resourcepack included with the mod for vanilla blocks for an example of the format as well as sound types you can use.

**Comment by CliffracerX** [comment]
Will see what I can do then, thanks for telling me.

Kind of a weird issue, hope it's fixable!  I see a lot of people on the forum topic complaining about their games crashing.  :(
